export const courseMeta = {
  title: "The 20 Values of Inner Freedom",
  subtitle: "Jnana Values from the Bhagavad Gita",
  description:
    "A 20-lesson course based on the values that prepare the mind for Self-knowledge. In Vedanta, these are called jnanam, not knowledge itself, but the qualities that make knowledge possible.",
  duration: "20 Lessons",
};

export const lessons = [
  {
    slug: "amanitvam",
    number: 1,
    title: "Amanitvam - Freedom from Self-Importance",
    content: [
      "Amanitvam means absence of mana, the need for recognition or importance.",
      "In Vedanta, humility is not thinking low of yourself. It is freedom from the need to be seen as special.",
      "When the mind is occupied with how it appears, it cannot learn. It is already full.",
      "This value prepares the mind to receive knowledge without distortion.",
      "In daily life, this shows up as wanting validation, appreciation, and recognition.",
      "Practice: Do something quietly without needing acknowledgment.",
      "Reflection: Can I be at ease without being important in this moment?",
    ],
  },
  {
    slug: "adambhitvam",
    number: 2,
    title: "Adambhitvam - Absence of Pretence",
    content: [
      "Adambhitvam means absence of dambha, showing what is not there.",
      "In Vedanta, pretence blocks learning because it replaces honesty with image.",
      "The mind becomes more concerned with appearing than understanding.",
      "This value brings simplicity and authenticity.",
      "In daily life, it shows up as exaggeration or projecting knowledge.",
      "Practice: Notice where you try to appear better than you are.",
      "Reflection: Where am I trying to appear instead of being real?",
    ],
  },
  {
    slug: "ahimsa",
    number: 3,
    title: "Ahimsa - Non-Harm",
    content: [
      "Ahimsa means non-injury in thought, word, and action.",
      "In Vedanta, it aligns with dharma, living in a way that does not create disturbance.",
      "Harm often comes from insecurity, fear, or reaction.",
      "A mind that harms cannot be quiet enough for knowledge.",
      "In daily life, this shows up as anger, harsh words, or silent resentment.",
      "Practice: Pause before reacting.",
      "Reflection: Was my response necessary and considerate?",
    ],
  },
  {
    slug: "ksantih",
    number: 4,
    title: "Ksantih - Acceptance",
    content: [
      "Ksantih means forbearance, the ability to accept what cannot be changed.",
      "In Vedanta, this aligns with Ishvara Prasada Buddhi, receiving results as given.",
      "Acceptance is not passivity. It is freedom from resistance.",
      "Resistance drains energy and blocks clarity.",
      "In daily life, it shows up as complaint and frustration.",
      "Practice: Acknowledge, 'This is what is given now.'",
      "Reflection: Can I respond without inner resistance?",
    ],
  },
  {
    slug: "arjavam",
    number: 5,
    title: "Arjavam - Straightforwardness",
    content: [
      "Arjavam means alignment between thought, word, and action.",
      "In Vedanta, crookedness creates inner conflict.",
      "Clarity requires inner simplicity.",
      "When there is no hidden agenda, the mind becomes lighter.",
      "In daily life, this shows up as saying one thing and meaning another.",
      "Practice: Be honest in small situations.",
      "Reflection: Am I aligned within?",
    ],
  },
  {
    slug: "acharyopasanam",
    number: 6,
    title: "Acharyopasanam - Reverence for the Teacher",
    content: [
      "Acharyopasanam means respect and service toward the teacher.",
      "In Vedanta, knowledge comes through a teaching tradition.",
      "This value opens the mind to receive knowledge properly.",
      "Without this attitude, learning becomes intellectual, not transformative.",
      "In daily life, it shows up as casualness toward guidance.",
      "Practice: Acknowledge what you have received from teachers.",
      "Reflection: Do I value the source of knowledge?",
    ],
  },
  {
    slug: "saucam",
    number: 7,
    title: "Saucam - Purity",
    content: [
      "Saucam means cleanliness, outer and inner.",
      "Outer purity is order and cleanliness.",
      "Inner purity is freedom from emotional clutter like resentment and agitation.",
      "A cluttered mind cannot see clearly.",
      "Practice: Clean one space and let go of one unnecessary thought.",
      "Reflection: What is cluttering my mind?",
    ],
  },
  {
    slug: "sthairyam",
    number: 8,
    title: "Sthairyam - Steadfastness",
    content: [
      "Sthairyam means stability and consistency.",
      "In Vedanta, inquiry requires a steady mind.",
      "Without steadiness, the mind keeps shifting and never settles.",
      "Practice: Stay committed to one small discipline.",
      "Reflection: Can I stay with what I begin?",
    ],
  },
  {
    slug: "atmavinigrahah",
    number: 9,
    title: "Atmavinigrahah - Self-Mastery",
    content: [
      "Atmavinigrahah means mastery over the mind and senses.",
      "It is not suppression, but intelligent regulation.",
      "Without mastery, the mind is driven by impulses.",
      "A driven mind cannot inquire.",
      "Practice: Delay one impulse today.",
      "Reflection: Who is in charge, me or my impulses?",
    ],
  },
  {
    slug: "vairagyam",
    number: 10,
    title: "Vairagyam - Dispassion",
    content: [
      "Vairagyam means freedom from dependence on objects.",
      "It does not mean rejection, but enjoyment without dependence.",
      "In Vedanta, this arises from seeing the limitations of everything.",
      "Objects cannot give lasting fulfillment.",
      "Practice: Notice where you expect lasting happiness from something.",
      "Reflection: Am I depending on this for happiness?",
    ],
  },
  {
    slug: "anahankarah",
    number: 11,
    title: "Anahankarah - Freedom from Ego",
    content: [
      "Anahankarah means absence of strong ego-identification.",
      "Ego is taking oneself to be roles, achievements, or labels.",
      "Vedanta points out that these are changing, not the Self.",
      "Practice: Observe your roles without identifying with them.",
      "Reflection: Who am I without these roles?",
    ],
  },
  {
    slug: "duhkha-darsanam",
    number: 12,
    title: "Reflection on Life's Limits",
    content: [
      "This value is reflection on birth, aging, illness, and death.",
      "In Vedanta, this removes unrealistic expectations from life.",
      "Everything in time is subject to change.",
      "Seeing this clearly brings maturity.",
      "Practice: Reflect on impermanence.",
      "Reflection: What am I expecting from life?",
    ],
  },
  {
    slug: "asaktih",
    number: 13,
    title: "Asaktih - Non-Attachment",
    content: [
      "Asaktih means absence of ownership.",
      "In Vedanta, nothing truly belongs to the individual.",
      "Everything is part of a larger order.",
      "Practice: Replace 'mine' with 'given'.",
      "Reflection: What am I holding onto?",
    ],
  },
  {
    slug: "anabhisvangah",
    number: 14,
    title: "Anabhisvangah - Non-Dependence",
    content: [
      "Anabhisvangah means absence of emotional dependence.",
      "Vedanta allows love, but not dependence.",
      "Dependence creates fear and insecurity.",
      "Practice: Appreciate without clinging.",
      "Reflection: Is this love or dependence?",
    ],
  },
  {
    slug: "samacittatvam",
    number: 15,
    title: "Samacittatvam - Equanimity",
    content: [
      "Samacittatvam means balance in all situations.",
      "It is central to Karma Yoga.",
      "Results are not always in our control.",
      "A steady mind remains unaffected.",
      "Practice: Observe reactions to success and failure.",
      "Reflection: Can I stay balanced?",
    ],
  },
  {
    slug: "bhakti",
    number: 16,
    title: "Bhakti - Devotion",
    content: [
      "Bhakti means devotion to Ishvara.",
      "In Vedanta, it is recognizing the total order.",
      "It brings surrender and reduces burden.",
      "Practice: Offer one action consciously.",
      "Reflection: Can I act as an offering?",
    ],
  },
  {
    slug: "viviktadesa",
    number: 17,
    title: "Vivikta-desa-sevitvam - Love for Solitude",
    content: [
      "This means preference for a quiet place.",
      "Solitude supports reflection and clarity.",
      "Constant noise keeps the mind outward.",
      "Practice: Spend time in silence.",
      "Reflection: Am I comfortable being alone?",
    ],
  },
  {
    slug: "arati",
    number: 18,
    title: "Aratih - Freedom from Social Dependence",
    content: [
      "Aratih means reduced need for constant social engagement.",
      "It is not isolation, but independence.",
      "The mind becomes less dependent on external validation.",
      "Practice: Reduce unnecessary interaction.",
      "Reflection: Am I avoiding myself?",
    ],
  },
  {
    slug: "tattva-jnana",
    number: 19,
    title: "Commitment to Self-Knowledge",
    content: [
      "This means commitment to understanding truth.",
      "In Vedanta, this is the central pursuit.",
      "Without commitment, the mind remains distracted.",
      "Practice: Set time for study.",
      "Reflection: What truly matters to me?",
    ],
  },
  {
    slug: "adhyatma-jnana",
    number: 20,
    title: "Adhyatma-jnana - Seeing Knowledge as the Goal",
    content: [
      "This is understanding Self-knowledge as the highest pursuit.",
      "Vedanta teaches that freedom is recognition, not achievement.",
      "All pursuits ultimately seek lasting fulfillment.",
      "Practice: Reflect on what is permanent.",
      "Reflection: What am I really seeking?",
    ],
  },
];

export function getLessonBySlug(slug) {
  return lessons.find((lesson) => lesson.slug === slug);
}
