export const courseTitle = "Aparokshanubhuti — Direct Knowledge of the Self";

export const courseDescription =
  "A 45-day guided unfolding of self-knowledge based on Aparokshanubhuti, presented in a calm and simple way.";

export const courseIntro = [
  "Aparokshanubhuti is a traditional Advaita Vedanta text that unfolds the direct knowledge of the Self. This course presents that teaching in a simple, step-by-step way.",
  "It is not about adopting a belief or chasing a special experience. It is about clear seeing — the recognition of what you already are.",
  "These 45 lessons move from preparation and inquiry to knowledge, assimilation, and living freedom.",
];

export const courseOrientation =
  "You can move through the course in order, one day at a time, or return to any lesson whenever needed.";

export const moduleOrder = [
  "Readiness for Knowledge",
  "The Problem of Ignorance",
  "Atma–Anatma Viveka",
  "The Nature of Reality",
  "Practice and Assimilation",
  "Living Knowledge",
];

export const lessons = [
  {
    slug: "day-1",
    day: 1,
    title: "What is Direct Knowledge?",
    module: "Readiness for Knowledge",
    reflection: "Is there ever a moment when you are absent to yourself?",
    takeaway: "The Self is not reached. It is recognized.",
    body: [
      "Most things in life are known indirectly.",
      "You see objects, hear sounds, think thoughts.",
      "But the Self is not an object.",
      "It is not something you can see, reach, or experience as separate from you.",
      "It is you, the one to whom every experience appears.",
      "Direct knowledge does not mean gaining something new.",
      "It means recognizing what is already present.",
      "You do not become the Self.",
      "You discover that you were never anything else.",
    ],
  },
  {
    slug: "day-2",
    day: 2,
    title: "Why Action Cannot Give Freedom",
    module: "Readiness for Knowledge",
    reflection: "Can something permanent come from something temporary?",
    takeaway: "Freedom is not produced. It is understood.",
    body: [
      "In life, action produces results.",
      "Effort leads to outcomes.",
      "But every result of action is limited.",
      "It begins, it changes, and it ends.",
      "If freedom were the result of action, it would also be temporary.",
      "But freedom is not something that comes and goes.",
      "It is not an achievement in time.",
      "What is gained can be lost.",
      "What is already present does not need to be gained.",
      "Action can prepare the mind.",
      "But only knowledge removes ignorance.",
    ],
  },
  {
    slug: "day-3",
    day: 3,
    title: "The Role of Knowledge",
    module: "Readiness for Knowledge",
    reflection: "What changes when a misunderstanding is corrected?",
    takeaway: "Knowledge does not create freedom. It reveals it.",
    body: [
      "If the problem is ignorance, the solution must be knowledge.",
      "Ignorance is not removed by action.",
      "It is removed only by seeing clearly.",
      "When you mistake a rope for a snake, no action is needed to remove the snake.",
      "You only need to see correctly.",
      "In the same way, the sense of limitation comes from not knowing your true nature.",
      "Knowledge does not change you.",
      "It corrects your understanding of yourself.",
    ],
  },
  {
    slug: "day-4",
    day: 4,
    title: "Qualification of the Seeker",
    module: "Readiness for Knowledge",
    reflection:
      "Is your mind available for clear seeing, or constantly pulled outward?",
    takeaway: "A prepared mind recognizes truth more easily.",
    body: [
      "Not every mind is ready to receive this knowledge.",
      "This is not because the truth is hidden, but because the mind may be distracted, reactive, or unsteady.",
      "A prepared mind is calm, clear, and capable of inquiry.",
      "It can listen without resistance, reflect without confusion, and stay with the teaching.",
      "This readiness is called qualification.",
      "It is not about perfection.",
      "It is about maturity.",
    ],
  },
  {
    slug: "day-5",
    day: 5,
    title: "Viveka (Discrimination)",
    module: "Readiness for Knowledge",
    reflection:
      "What in your experience is always present, no matter what changes?",
    takeaway:
      "Clarity begins by separating the changing from the unchanging.",
    body: [
      "The first step in clarity is discrimination.",
      "Discrimination means seeing the difference between what is changing and what is unchanging.",
      "The body changes.",
      "Thoughts change.",
      "Emotions change.",
      "But the one who knows these changes does not come and go.",
      "Without this distinction, everything gets mixed together.",
      "And confusion continues.",
      "With this distinction, clarity begins.",
    ],
  },
  {
    slug: "day-6",
    day: 6,
    title: "Vairagya (Dispassion)",
    module: "Readiness for Knowledge",
    reflection: "What do you still expect will finally make you complete?",
    takeaway:
      "Dispassion is not withdrawal. It is freedom from dependence.",
    body: [
      "Dispassion does not mean rejecting life.",
      "It means understanding its limits.",
      "Every experience gives temporary satisfaction.",
      "But no experience gives lasting completeness.",
      "When this is clearly seen, dependence begins to drop.",
      "You still act, enjoy, and participate.",
      "But you no longer expect life to complete you.",
      "This quiet freedom from dependence is vairagya.",
    ],
  },
  {
    slug: "day-7",
    day: 7,
    title: "Mumukshutva (Desire for Freedom)",
    module: "Readiness for Knowledge",
    reflection: "Is your search for comfort, or for freedom?",
    takeaway: "A clear desire for freedom brings direction to life.",
    body: [
      "Everyone wants happiness.",
      "But not everyone clearly wants freedom.",
      "Freedom means no longer depending on anything to be okay.",
      "When this becomes important, the search becomes focused.",
      "This deep desire for freedom is mumukshutva.",
      "It is not emotional intensity.",
      "It is clarity about what truly matters.",
    ],
  },
  {
    slug: "day-8",
    day: 8,
    title: "What is Ignorance (Avidya)?",
    module: "The Problem of Ignorance",
    reflection: "What do you take yourself to be, without questioning it?",
    takeaway:
      "Ignorance is not absence of knowledge. It is wrong self-understanding.",
    body: [
      "Ignorance does not mean lack of information.",
      "It means not knowing your true nature.",
      "Because of this, you take yourself to be limited, incomplete, and dependent.",
      "This misunderstanding shapes how you see everything.",
      "Ignorance is not something you feel directly.",
      "It shows up as confusion about who you are.",
    ],
  },
  {
    slug: "day-9",
    day: 9,
    title: "How Bondage Happens",
    module: "The Problem of Ignorance",
    reflection: "What changes when you identify with the body and mind?",
    takeaway:
      "Bondage is not real. It is a result of misidentification.",
    body: [
      "Bondage is not a physical condition.",
      "It is a mistaken sense of limitation.",
      "When you take yourself to be the body and mind, you also take on their limitations.",
      "You feel small, vulnerable, and incomplete.",
      "From this, desire and fear arise.",
      "And life becomes a constant effort to fix yourself.",
    ],
  },
  {
    slug: "day-10",
    day: 10,
    title: "Confusion of Self and Not-Self",
    module: "The Problem of Ignorance",
    reflection: "If something is known to you, can it be you?",
    takeaway: "Freedom begins by separating Self from not-Self.",
    body: [
      "The core problem is simple.",
      "The Self and not-Self are mixed up.",
      "You take what is not you to be you.",
      "The body is known, but you say, \"I am the body.\"",
      "Thoughts are known, but you say, \"I am thinking.\"",
      "This confusion creates all further problems.",
    ],
  },
  {
    slug: "day-11",
    day: 11,
    title: "Jiva, Jagat, Ishvara",
    module: "The Problem of Ignorance",
    reflection:
      "Do you see life as random, or as part of a larger order?",
    takeaway:
      "Understanding life requires seeing the individual, the world, and the order together.",
    body: [
      "Your experience can be seen in three parts.",
      "Jiva, the individual.",
      "Jagat, the world.",
      "Ishvara, the total order.",
      "You experience yourself as a person, interacting with a world, governed by an order you do not control.",
      "Without understanding this clearly, confusion continues.",
      "This teaching will unfold the truth of all three.",
    ],
  },
  {
    slug: "day-12",
    day: 12,
    title: "The Root Problem: Misidentification",
    module: "The Problem of Ignorance",
    reflection:
      "What if the problem is not life, but how you see yourself?",
    takeaway: "Misidentification is the root of all limitation.",
    body: [
      "All problems trace back to one error.",
      "You take yourself to be what you are not.",
      "Because of this, you feel limited, seek completion, and struggle with life.",
      "But the error is not in the world.",
      "It is in understanding.",
      "When the mistake is corrected, nothing new is gained.",
      "But everything is seen differently.",
    ],
  },
  {
    slug: "day-13",
    day: 13,
    title: "What is the Self (Atma)?",
    module: "Atma–Anatma Viveka",
    reflection:
      "What is always present, no matter what you experience?",
    takeaway: "The Self is the unchanging knower in all experiences.",
    body: [
      "The Self is not something you experience.",
      "It is that because of which all experience is known.",
      "It is present in every experience, but is not limited by any experience.",
      "It does not come and go.",
      "It does not change.",
      "It is the constant presence in waking, dream, and sleep.",
      "It is not an object.",
      "It is you, the knower of all objects.",
    ],
  },
  {
    slug: "day-14",
    day: 14,
    title: "What is Not-Self (Anatma)?",
    module: "Atma–Anatma Viveka",
    reflection: "Can something that comes and goes be who you are?",
    takeaway: "The changing and the known belong to not-Self.",
    body: [
      "Not-Self includes everything that is known to you.",
      "The body is known.",
      "The mind is known.",
      "Thoughts, emotions, and sensations are known.",
      "What is known cannot be the knower.",
      "All that changes, appears, and disappears belongs to not-Self.",
      "This includes everything you experience.",
    ],
  },
  {
    slug: "day-15",
    day: 15,
    title: "You Are Not the Body",
    module: "Atma–Anatma Viveka",
    reflection: "If the body is known to you, how can it be you?",
    takeaway: "The body is an object of knowledge, not the Self.",
    body: [
      "The body is constantly changing.",
      "It grows, ages, and undergoes many conditions.",
      "Yet you say, \"my body.\"",
      "What is owned is different from the owner.",
      "The body is known to you.",
      "It is experienced like any other object.",
      "You are the knower of the body, not the body itself.",
    ],
  },
  {
    slug: "day-16",
    day: 16,
    title: "You Are Not the Mind",
    module: "Atma–Anatma Viveka",
    reflection:
      "Are you changing with every thought, or aware of thoughts?",
    takeaway: "The mind is an object of awareness, not the Self.",
    body: [
      "Thoughts arise and pass.",
      "Emotions come and go.",
      "Sometimes the mind is clear.",
      "Sometimes it is disturbed.",
      "But you are aware of all these changes.",
      "That which is observed cannot be the observer.",
      "The mind is known to you.",
      "It is not you.",
    ],
  },
  {
    slug: "day-17",
    day: 17,
    title: "The Witness (Sakshi)",
    module: "Atma–Anatma Viveka",
    reflection:
      "What is present even when your thoughts change completely?",
    takeaway: "You are the witness of all experiences.",
    body: [
      "The witness is the one to whom everything appears.",
      "Thoughts appear.",
      "Emotions appear.",
      "The body appears.",
      "The witness does not act.",
      "It does not change.",
      "It simply knows.",
      "It is present in every experience, without being affected by any experience.",
    ],
  },
  {
    slug: "day-18",
    day: 18,
    title: "Seer and Seen",
    module: "Atma–Anatma Viveka",
    reflection: "Can the seer ever become an object of seeing?",
    takeaway: "The seer is different from everything that is seen.",
    body: [
      "Everything in your experience can be divided into two: the seer and the seen.",
      "The seen is whatever is known.",
      "The seer is the one who knows.",
      "The body is seen.",
      "The mind is seen.",
      "Thoughts are seen.",
      "The seer is never seen.",
      "It is the constant knower behind all experiences.",
    ],
  },
  {
    slug: "day-19",
    day: 19,
    title: "The Three Bodies",
    module: "Atma–Anatma Viveka",
    reflection: "Are you any of these, or the one who knows them?",
    takeaway: "The Self is different from all three bodies.",
    body: [
      "Your experience can be understood through three bodies.",
      "The gross body, the physical body.",
      "The subtle body, the mind, senses, and thoughts.",
      "The causal body, the state of ignorance.",
      "All three are known to you.",
      "They change, appear, and disappear.",
      "You are the one to whom all three are revealed.",
    ],
  },
  {
    slug: "day-20",
    day: 20,
    title: "The Three States",
    module: "Atma–Anatma Viveka",
    reflection: "What is common to all three states?",
    takeaway: "You are the constant presence across all states.",
    body: [
      "You experience three states: waking, dream, and deep sleep.",
      "Each state comes and goes.",
      "But you are present in all three.",
      "You say, \"I was awake,\" \"I dreamt,\" \"I slept well.\"",
      "The states change.",
      "The knower of the states does not.",
    ],
  },
  {
    slug: "day-21",
    day: 21,
    title: "Changing and Unchanging",
    module: "Atma–Anatma Viveka",
    reflection:
      "What remains the same while everything else changes?",
    takeaway: "The unchanging knower is the Self.",
    body: [
      "Everything you experience is changing.",
      "The body changes.",
      "The mind changes.",
      "The world changes.",
      "Change can only be known if something does not change.",
      "That unchanging presence is you.",
      "Without it, no change could ever be known.",
    ],
  },
  {
    slug: "day-22",
    day: 22,
    title: "You Are the Knower, Not the Known",
    module: "Atma–Anatma Viveka",
    reflection:
      "Can the knower ever be turned into something known?",
    takeaway: "You are the knower of all, never the known.",
    body: [
      "Everything known to you is an object.",
      "The body is known.",
      "The mind is known.",
      "The world is known.",
      "The knower is never known as an object.",
      "It is self-evident.",
      "It is always present.",
      "You are that knower.",
    ],
  },
  {
    slug: "day-23",
    day: 23,
    title: "What is Brahman?",
    module: "The Nature of Reality",
    reflection:
      "What must be present for anything to exist or be known?",
    takeaway:
      "Brahman is the unchanging reality behind all experience.",
    body: [
      "Brahman is the word used to point to the ultimate reality.",
      "It is not an object.",
      "It is not somewhere else.",
      "It is that because of which everything exists and is known.",
      "It does not come and go.",
      "It does not change.",
      "It is limitless existence and awareness.",
    ],
  },
  {
    slug: "day-24",
    day: 24,
    title: "The Self is Brahman",
    module: "The Nature of Reality",
    reflection:
      "Is the awareness in you different from awareness anywhere else?",
    takeaway: "The Self and Brahman are not different.",
    body: [
      "The teaching now makes a bold statement.",
      "The Self you discovered as the witness is not separate from Brahman.",
      "There are not two realities.",
      "The same awareness that knows your thoughts is the reality of everything.",
      "This is not a belief.",
      "It is to be understood clearly.",
    ],
  },
  {
    slug: "day-25",
    day: 25,
    title: "The World as Appearance",
    module: "The Nature of Reality",
    reflection:
      "Does the world exist independently of awareness?",
    takeaway: "The world is an appearance dependent on reality.",
    body: [
      "The world is experienced.",
      "It is known, changing, and dependent.",
      "Anything that depends on something else for its existence is not independent reality.",
      "The world appears in awareness, just like thoughts appear in the mind.",
      "This does not mean the world is not there.",
      "It means it is not absolute.",
    ],
  },
  {
    slug: "day-26",
    day: 26,
    title: "The Rope and the Snake",
    module: "The Nature of Reality",
    reflection: "What happens to fear when the truth is known?",
    takeaway: "Error disappears when reality is clearly seen.",
    body: [
      "In dim light, a rope is mistaken for a snake.",
      "Fear arises.",
      "Reactions follow.",
      "But when the rope is seen clearly, the snake disappears.",
      "The snake was never real.",
      "It only appeared due to misunderstanding.",
      "In the same way, limitation appears real because the Self is not understood.",
    ],
  },
  {
    slug: "day-27",
    day: 27,
    title: "Cause and Effect",
    module: "The Nature of Reality",
    reflection: "Can an effect exist without its cause?",
    takeaway:
      "The world is not separate from its underlying reality.",
    body: [
      "Every effect depends on a cause.",
      "A pot depends on clay.",
      "Without clay, there is no pot.",
      "But clay does not depend on the pot.",
      "In the same way, the world depends on reality, but reality does not depend on the world.",
      "The effect is not separate from the cause.",
    ],
  },
  {
    slug: "day-28",
    day: 28,
    title: "Non-Duality (Advaita)",
    module: "The Nature of Reality",
    reflection:
      "If everything depends on one reality, can there be two?",
    takeaway: "Reality is one, without a second.",
    body: [
      "Duality means two separate realities.",
      "But if everything depends on one reality, there cannot be two independent things.",
      "The Self is not one among many.",
      "It is the only reality, appearing as everything.",
      "This is non-duality.",
    ],
  },
  {
    slug: "day-29",
    day: 29,
    title: "The End of Separation",
    module: "The Nature of Reality",
    reflection: "What creates the feeling of being separate?",
    takeaway: "Separation ends when the Self is understood.",
    body: [
      "Separation is felt because of identification with the body and mind.",
      "When you see yourself as limited, everything else appears separate.",
      "But when you recognize yourself as awareness, the sense of separation begins to dissolve.",
      "The same reality appears as everything.",
      "Nothing is truly outside you.",
    ],
  },
  {
    slug: "day-30",
    day: 30,
    title: "What is Freedom (Moksha)?",
    module: "The Nature of Reality",
    reflection:
      "What if nothing needs to change for you to be complete?",
    takeaway: "Freedom is the end of the sense of limitation.",
    body: [
      "Freedom is not becoming something new.",
      "It is not reaching a different state.",
      "It is the recognition that you were never limited.",
      "The search ends, not because something is gained, but because confusion is removed.",
      "Life continues.",
      "But the sense of lack is gone.",
    ],
  },
  {
    slug: "day-31",
    day: 31,
    title: "Why Assimilation is Needed",
    module: "Practice and Assimilation",
    reflection: "Where do you still react from old patterns?",
    takeaway: "Assimilation makes knowledge steady.",
    body: [
      "Understanding may be clear, but old habits of thinking can continue.",
      "You may know you are not the body, yet still react as if you are.",
      "This is not a lack of knowledge, but a habit of identification.",
      "Assimilation removes this gap.",
      "It allows knowledge to become natural.",
    ],
  },
  {
    slug: "day-32",
    day: 32,
    title: "Nididhyasana (Assimilation)",
    module: "Practice and Assimilation",
    reflection:
      "Can you stay with what you already know to be true?",
    takeaway:
      "Nididhyasana is living with clarity, not seeking new experience.",
    body: [
      "Nididhyasana is not creating a new experience.",
      "It is staying with what has already been understood.",
      "Again and again, you bring the mind back to the truth.",
      "Not by force, but by clarity.",
      "It is a quiet re-alignment with knowledge.",
    ],
  },
  {
    slug: "day-33",
    day: 33,
    title: "Dropping Wrong Notions",
    module: "Practice and Assimilation",
    reflection:
      "What false idea about yourself still feels real?",
    takeaway: "Freedom comes by dropping what is not true.",
    body: [
      "The problem is not lack of truth.",
      "It is holding on to what is not true.",
      "\"I am limited.\"",
      "\"I am incomplete.\"",
      "These ideas continue out of habit.",
      "They are to be seen clearly and dropped.",
    ],
  },
  {
    slug: "day-34",
    day: 34,
    title: "Seeing Everything as Reality",
    module: "Practice and Assimilation",
    reflection:
      "Can you see the same reality in all experiences?",
    takeaway: "Everything is an expression of one reality.",
    body: [
      "Reality is not somewhere else.",
      "Everything you experience is not separate from reality.",
      "Names and forms change, but the underlying reality does not.",
      "Just as all ornaments are gold, everything is nothing but reality.",
      "This vision removes division.",
    ],
  },
  {
    slug: "day-35",
    day: 35,
    title: "What is Meditation?",
    module: "Practice and Assimilation",
    reflection:
      "Can clarity remain even when the mind is active?",
    takeaway:
      "Meditation is clarity about the Self, not control of the mind.",
    body: [
      "Meditation is often seen as controlling the mind.",
      "But here, it is understanding the mind.",
      "The mind is allowed to be as it is, while you remain clear about who you are.",
      "It is not about silence.",
      "It is about clarity.",
      "Even in activity, this clarity can remain.",
    ],
  },
  {
    slug: "day-36",
    day: 36,
    title: "What is Yoga?",
    module: "Practice and Assimilation",
    reflection:
      "Can something already whole become more whole?",
    takeaway: "Yoga is recognizing what is already complete.",
    body: [
      "Yoga is often understood as union.",
      "But what is already one does not need to be united.",
      "The real problem is not separation, but the belief in separation.",
      "Yoga is the recognition of what is already true.",
      "It is clarity, not connection.",
    ],
  },
  {
    slug: "day-37",
    day: 37,
    title: "True Silence",
    module: "Practice and Assimilation",
    reflection: "What remains even when thoughts are present?",
    takeaway: "Silence is the nature of the Self.",
    body: [
      "Silence is not the absence of sound.",
      "Sounds come and go, but silence remains.",
      "In the same way, thoughts come and go, but awareness remains.",
      "True silence is this unchanging presence.",
      "It is always there.",
    ],
  },
  {
    slug: "day-38",
    day: 38,
    title: "Steady Vision",
    module: "Practice and Assimilation",
    reflection: "Does your understanding change with circumstances?",
    takeaway: "Steady knowledge is not affected by change.",
    body: [
      "Knowledge becomes firm when it is not shaken by situations.",
      "Life will continue to change.",
      "But your understanding need not change with it.",
      "This stability is steady vision.",
      "It is clarity that remains through all conditions.",
    ],
  },
  {
    slug: "day-39",
    day: 39,
    title: "Dissolving Duality",
    module: "Practice and Assimilation",
    reflection: "What creates the sense of \"other\"?",
    takeaway: "Duality is resolved through right understanding.",
    body: [
      "Duality appears as subject and object, self and other.",
      "But this division is based on misunderstanding.",
      "When the Self is known, the division loses its hold.",
      "Experience continues, but without separation.",
      "This is freedom from duality.",
    ],
  },
  {
    slug: "day-40",
    day: 40,
    title: "Effort to Effortlessness",
    module: "Practice and Assimilation",
    reflection: "Can being yourself require effort?",
    takeaway: "Effort ends when clarity is complete.",
    body: [
      "In the beginning, effort is needed to understand.",
      "You listen, reflect, and stay with the teaching.",
      "But once clarity is firm, effort drops.",
      "You no longer try to be yourself.",
      "You simply are.",
    ],
  },
  {
    slug: "day-41",
    day: 41,
    title: "What is a Jnani?",
    module: "Living Knowledge",
    reflection:
      "What would life be like without a sense of lack?",
    takeaway:
      "A jnani is free in understanding, not different in appearance.",
    body: [
      "A jnani is not someone special.",
      "It is one who knows the truth clearly.",
      "The body and mind continue, but the sense of limitation is gone.",
      "Life is lived, but without inner dependence.",
      "Knowledge is firm and natural.",
    ],
  },
  {
    slug: "day-42",
    day: 42,
    title: "Freedom While Living",
    module: "Living Knowledge",
    reflection:
      "Can freedom depend on changing life situations?",
    takeaway: "Freedom is independent of circumstances.",
    body: [
      "Freedom is not after life.",
      "It is here, while living.",
      "Situations continue.",
      "Experiences continue.",
      "But the inner sense of limitation is gone.",
      "This is freedom while living.",
    ],
  },
  {
    slug: "day-43",
    day: 43,
    title: "What Happens to Karma?",
    module: "Living Knowledge",
    reflection: "Who is affected when identification drops?",
    takeaway: "Karma continues, but bondage does not.",
    body: [
      "Actions continue, and their results continue.",
      "But the one who was bound by them is no longer taken to be real.",
      "The body and mind go through their course.",
      "But you are free from identification.",
      "This is freedom from karma.",
    ],
  },
  {
    slug: "day-44",
    day: 44,
    title: "Life After Knowledge",
    module: "Living Knowledge",
    reflection:
      "What if life does not need to change for peace to be present?",
    takeaway: "Peace is not in life. It is in understanding.",
    body: [
      "Life does not become perfect.",
      "It continues as before, with ups and downs.",
      "But the inner struggle ends.",
      "There is acceptance, clarity, and ease.",
      "Nothing needs to be added.",
    ],
  },
  {
    slug: "day-45",
    day: 45,
    title: "Abidance in the Self",
    module: "Living Knowledge",
    reflection: "Can you ever be away from yourself?",
    takeaway: "Abidance is natural when confusion is gone.",
    body: [
      "Abidance is not doing something.",
      "It is not maintaining a state.",
      "It is simply being clear about what you are.",
      "The Self is always present.",
      "There is nothing to hold on to.",
      "Nothing to achieve.",
      "Just clarity.",
    ],
  },
];

export const modules = moduleOrder.map((name) => {
  const moduleLessons = lessons.filter((lesson) => lesson.module === name);

  return {
    name,
    startDay: moduleLessons[0]?.day ?? null,
    endDay: moduleLessons[moduleLessons.length - 1]?.day ?? null,
    lessonCount: moduleLessons.length,
    lessons: moduleLessons,
  };
});

export function getLessonBySlug(slug) {
  return lessons.find((lesson) => lesson.slug === slug);
}

export function getLessonIndex(slug) {
  return lessons.findIndex((lesson) => lesson.slug === slug);
}
