const defaultFocus = "Source extraction from uploaded PDF";
const defaultNotes =
  "Verify Sanskrit, transliteration, verse number, and literal translation before publication.";

export const extractionQueue = [
  {
    batch: "Batch 4",
    days: [16, 17, 18, 19, 20],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 5",
    days: [21, 22, 23, 24, 25],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 6",
    days: [26, 27, 28, 29, 30],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 7",
    days: [31, 32, 33, 34, 35],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 8",
    days: [36, 37, 38, 39, 40],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 9",
    days: [41, 42, 43, 44, 45],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 10",
    days: [46, 47, 48, 49, 50],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 11",
    days: [51, 52, 53, 54, 55],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 12",
    days: [56, 57, 58, 59, 60],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 13",
    days: [61, 62, 63, 64, 65],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 14",
    days: [66, 67, 68, 69, 70],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 15",
    days: [71, 72, 73, 74, 75],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 16",
    days: [76, 77, 78, 79, 80],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 17",
    days: [81, 82, 83, 84, 85],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 18",
    days: [86, 87, 88, 89, 90],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 19",
    days: [91, 92, 93, 94, 95],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 20",
    days: [96, 97, 98, 99, 100],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 21",
    days: [101, 102, 103, 104, 105],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 22",
    days: [106, 107, 108, 109, 110],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
  {
    batch: "Batch 23",
    days: [111, 112],
    status: "not-started",
    focus: defaultFocus,
    notes: defaultNotes,
  },
];
